apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  nginx.conf: |
    server {
      listen 8080;

      location / {
        # First try with vanity.
        try_files =404 @vanity;
      }

      location @vanity {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://127.0.0.1:9192;
        proxy_intercept_errors on;
        recursive_error_pages on;

        set $pass 0;
        if ($arg_go-get = 1) {
          set $pass 1;
        }
        if ($request_uri ~ git-upload-pack) {
          set $pass 1;
        }
        if ($pass = 0) {
          return 404;
        }

        error_page 404 = @real_location;
      }

      location @real_location {
        # Fallback location for when vanity returns 404.
      }
    }
